{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafdrop.fullname" . }}
  labels:
    {{- include "kafdrop.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kafdrop.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kafdrop.selectorLabels" . | nindent 8 }}
        {{- if .Values.workloadIdentity.enabled }}
        azure.workload.identity/use: "true"
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: kafdrop
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          env:
            - name: KAFKA_BROKERCONNECT
              value: {{ .Values.kafkaBrokerConnect | quote }}
            - name: KAFKA_PROPERTIES_FILE
              value: /etc/kafdrop/kafka.properties
            - name: JVM_OPTS
              value: {{ printf "%s %s" .Values.jvmOpts .Values.extraJvmOpts | trim | quote }}
            - name: SERVER_SERVLET_CONTEXTPATH
              value: "/"
          volumeMounts:
            - name: kafka-config
              mountPath: /etc/kafdrop
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: kafka-config
          configMap:
            name: {{ include "kafdrop.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
