{{- if (index .Values "otel-collector" "enabled") }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: otel-collector-spc
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/part-of: middleware
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.global.workloadIdentity.clientId | quote }}
    keyvaultName: {{ .Values.global.keyvault.name | quote }}
    tenantId: {{ .Values.global.keyvault.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: appinsights-connection-string
          objectType: secret
  secretObjects:
    - secretName: otel-collector-secrets
      type: Opaque
      data:
        - objectName: appinsights-connection-string
          key: appinsights-connection-string
{{- end }}
